export const SERVER_ADD_LIGHT = 'SERVER_ADD_LIGHT';
export const SERVER_REMOVE_LIGHT = 'SERVER_REMOVE_LIGHT';
export const SERVER_UPDATE_LIGHT = 'SERVER_UPDATE_LIGHT';
export const SERVER_ALL_LIGHTS = 'SERVER_ALL_LIGHTS';
export const SERVER_LIGHT_COLOR = 'SERVER_LIGHT_COLOR';
export const SERVER_TOGGLE_LIGHT = 'SERVER_TOGGLE_LIGHT';
export const SERVER_LIGHT_ANIMATION  = 'SERVER_LIGHT_ANIMATION';
